apiVersion: batch/v1
kind: Job
metadata:
  name: ml-trainer-job
spec:
  template:
    spec:
      containers:
        - name: ml-model-trainer
          image: caiossferr/ml_model:0.1
          command: ["python", "train_model.py"]
          volumeMounts:
            - mountPath: /app/model
              name: model-storage
      restartPolicy: Never
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: project2-pv2-caioferreira
  backoffLimit: 4
