apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-deployment
  namespace: caioferreira
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playlist-recommender-cssf
  template:
    metadata:
      labels:
        app: playlist-recommender-cssf
    spec:
      initContainers:
        - name: ml-model-trainer
          image: caiossferr/ml_model:0.6
          volumeMounts:
            - mountPath: /app/model
              name: model-storage
          env:
            - name: DATASET_URL
              value: "https://raw.githubusercontent.com/caiossfer2/tp2_nuvem/master/datasets/2023_spotify_ds1.csv"
      containers:
        - name: playlist-recommender-api
          image: caiossferr/api:0.6
          ports:
            - containerPort: 52008
          volumeMounts:
            - mountPath: /app/model
              name: model-storage
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: project2-pv2-caioferreira
