apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: caioferreira
  name: project2-pv2-caioferreira
  labels:
    type: local
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      namespace: caioferreira
