apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: caioferreira
  name: project2-pv2-caioferreira
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-caioferreira
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      namespace: caioferreira
  volumeName: project2-pv2-caioferreira
