apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  # type: LoadBalancer
  selector:
    app: playlist-recommender-api
  ports:
    - protocol: TCP
      port: 52008
      targetPort: 52008
