apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playlist-recommender-api
  template:
    metadata:
      labels:
        app: playlist-recommender-api
    spec:
      containers:
        - name: playlist-recommender-api
          image: caiossferr/api:0.1
          ports:
            - containerPort: 52008
